#!/bin/env bash

feh -B black -R 2 --scale-down --g 300x300 /tmp/albumart &
disown %1
#mpd music directory
musicdir="/home/zoe/music"

for pid in $(ps -ef | grep "mpdvis" | awk '{print $2}')
do
	[ "$pid" != $$ ] && kill $pid
done

#################
#if ran with 0 arg, put current album art into /tmp/albumart
while true
do
	songdir=$(mpc -f %file%)
	if [ -f "/home/zoe/music/$songdir/*.png" ] 
	then
		cp "$musicdir"/"${songdir%%/*}"/*.png /tmp/albumart
	else
		cp "$musicdir"/"${songdir%%/*}"/*.jpg /tmp/albumart
	fi
	sleep 2
done
